// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['AiChannelBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['AiChannelBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['AiChannelBiz']['Edit'](arg1);
}

export function FindByUrl(arg1) {
  return window['go']['biz']['AiChannelBiz']['FindByUrl'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['AiChannelBiz']['Get'](arg1);
}

export function GetList() {
  return window['go']['biz']['AiChannelBiz']['GetList']();
}

export function Page(arg1) {
  return window['go']['biz']['AiChannelBiz']['Page'](arg1);
}
