// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean() {
  return window['go']['biz']['ChatBiz']['Clean']();
}

export function GetImage(arg1) {
  return window['go']['biz']['ChatBiz']['GetImage'](arg1);
}

export function Upload(arg1) {
  return window['go']['biz']['ChatBiz']['Upload'](arg1);
}
