// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean():Promise<void>;

export function GetImage(arg1:string):Promise<any>;

export function Upload(arg1:{[key: string]: string}):Promise<any>;
