// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['CollectionBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['CollectionBiz']['Delete'](arg1);
}

export function GetList() {
  return window['go']['biz']['CollectionBiz']['GetList']();
}

export function Upload(arg1, arg2) {
  return window['go']['biz']['CollectionBiz']['Upload'](arg1, arg2);
}
