// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Add(arg1:string):Promise<model.HttpResult>;

export function Delete(arg1:string):Promise<model.HttpResult>;

export function GetList():Promise<model.HttpResult>;

export function Upload(arg1:string,arg2:{[key: string]: string}):Promise<any>;
