// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {model} from '../models';
import {sql} from '../models';
import {dv} from '../models';
import {biz} from '../models';

export function Add(arg1:entity.DbConfig):Promise<model.HttpResult>;

export function Delete(arg1:string):Promise<model.HttpResult>;

export function Edit(arg1:entity.DbConfig):Promise<model.HttpResult>;

export function FindByConfig(arg1:string):Promise<entity.DbConfig>;

export function Get(arg1:string):Promise<model.HttpResult>;

export function GetConnect(arg1:string,arg2:string):Promise<sql.DB>;

export function GetList():Promise<model.HttpResult>;

export function GetTableDetail(arg1:string,arg2:Array<any>):Promise<string>;

export function GetTables(arg1:string):Promise<Array<dv.TableInfo>>;

export function Page(arg1:biz.DbDataSourceQuery):Promise<model.HttpResult>;

export function QueryExecSql(arg1:string,arg2:string):Promise<string>;

export function QuerySql(arg1:sql.DB,arg2:string):Promise<Array<{[key: string]: string}>>;
