// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['DbConfigBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['DbConfigBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['DbConfigBiz']['Edit'](arg1);
}

export function FindByConfig(arg1) {
  return window['go']['biz']['DbConfigBiz']['FindByConfig'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['DbConfigBiz']['Get'](arg1);
}

export function GetConnect(arg1, arg2) {
  return window['go']['biz']['DbConfigBiz']['GetConnect'](arg1, arg2);
}

export function GetList() {
  return window['go']['biz']['DbConfigBiz']['GetList']();
}

export function GetTableDetail(arg1, arg2) {
  return window['go']['biz']['DbConfigBiz']['GetTableDetail'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['biz']['DbConfigBiz']['GetTables'](arg1);
}

export function Page(arg1) {
  return window['go']['biz']['DbConfigBiz']['Page'](arg1);
}

export function QueryExecSql(arg1, arg2) {
  return window['go']['biz']['DbConfigBiz']['QueryExecSql'](arg1, arg2);
}

export function QuerySql(arg1, arg2) {
  return window['go']['biz']['DbConfigBiz']['QuerySql'](arg1, arg2);
}
