// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {model} from '../models';
import {biz} from '../models';

export function Add(arg1:entity.Document):Promise<model.HttpResult>;

export function Delete(arg1:string):Promise<model.HttpResult>;

export function DeleteByCollection(arg1:string):Promise<model.HttpResult>;

export function Edit(arg1:entity.Document):Promise<model.HttpResult>;

export function Get(arg1:string):Promise<model.HttpResult>;

export function GetList(arg1:string):Promise<model.HttpResult>;

export function Page(arg1:biz.DocumentQuery):Promise<model.HttpResult>;
