// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['DocumentBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['DocumentBiz']['Delete'](arg1);
}

export function DeleteByCollection(arg1) {
  return window['go']['biz']['DocumentBiz']['DeleteByCollection'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['DocumentBiz']['Edit'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['DocumentBiz']['Get'](arg1);
}

export function GetList(arg1) {
  return window['go']['biz']['DocumentBiz']['GetList'](arg1);
}

export function Page(arg1) {
  return window['go']['biz']['DocumentBiz']['Page'](arg1);
}
