// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['FunctionImplBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['FunctionImplBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['FunctionImplBiz']['Edit'](arg1);
}

export function FindByName(arg1) {
  return window['go']['biz']['FunctionImplBiz']['FindByName'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['FunctionImplBiz']['Get'](arg1);
}

export function GetList() {
  return window['go']['biz']['FunctionImplBiz']['GetList']();
}

export function Page(arg1) {
  return window['go']['biz']['FunctionImplBiz']['Page'](arg1);
}
