// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['FunctionBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['FunctionBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['FunctionBiz']['Edit'](arg1);
}

export function ExecFuncCall(arg1) {
  return window['go']['biz']['FunctionBiz']['ExecFuncCall'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['FunctionBiz']['Get'](arg1);
}

export function GetList() {
  return window['go']['biz']['FunctionBiz']['GetList']();
}

export function Page(arg1) {
  return window['go']['biz']['FunctionBiz']['Page'](arg1);
}
