// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['FwConfigBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['FwConfigBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['FwConfigBiz']['Edit'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['FwConfigBiz']['Get'](arg1);
}

export function GetList() {
  return window['go']['biz']['FwConfigBiz']['GetList']();
}

export function Page(arg1) {
  return window['go']['biz']['FwConfigBiz']['Page'](arg1);
}
